### ISSUE TITLE
Tracking AI Improvements

### ISSUE THREAD

**Issue by Caleb-T-Owens** [gitbutlerapp/gitbutler#3255]
The greater context:
Listed below are a series of smaller changes which after some initial investigation appear to be prerequisites for enabling the use of custom AI endpoints. This is primarily due to the fact that these models are quite a bit weaker and have smaller context windows.

- [x] Have configuration options around patch length. OpenAI and Anthropic models support very large contexts, but these open models have smaller contexts, and ollama will cut off the start of your prompt if it is too long causing it to generate rubbish. For these models to be even remotely useful we need to make the amount of context provided configurable.

  To me it seems like it would make sense to keep the current default of length 5000 characters when going through GitButler API, but then having separate configurable options for BYO key OpenAI, Anthropic, and custom endpoints.
- [x] Shuffling the hunks before we take a slice of the patch file. If we’re only taking 1000 characters of the patch file, it may only get one file out of five or six and only cover one change. Shuffling the order of the inputs doesn’t seem to reduce the quality of the output for Anthropic and OpenAI and helps them summarise the changes more generally.
  -  Will be completed by https://github.com/gitbutlerapp/gitbutler/pull/3254
- [x] Allow customising the prompt templates. I found that with the weaker models, they struggled with some of the instructions around which tense to use, and required more specific requirements for the title and punctuation. For these weaker models to be of any use we’re going to need to have the ability for people to change these prompts to better leverage specific models.
- [x] Something that isn’t so much of a dependency, but I found that by adding a hunk’s file name to the top of each hunk enabled the Anthropic and OpenAI models to actually reference where changes were made which was very pleasing to see.
  - Will be completed by https://github.com/gitbutlerapp/gitbutler/pull/3254
