### ISSUE TITLE
[Research|Draft] The great refactor (for lack of a better title)

### ISSUE THREAD

**Issue by Byron** [gitbutlerapp/gitbutler#3957]
## Tasks

* [x] multi-instance safety: prevent multiple instance (or Windows within an application) to look at the same 
    - [x] https://github.com/gitbutlerapp/gitbutler/pull/4316
* [x] decide on `&mut` or file-locks, evaluate pros/cons together.
    - [x] PoC PR: https://github.com/gitbutlerapp/gitbutler/pull/4349
* Upgradable and Downgradable locking to better represent that some read-only methods may write
    - [x] #4410 

### Added Disk-State

The following is a list of all state added in the PRs above. It lives in `.git/gitbutler`

* **window.lock**
    - exclusive access of projects, one per Window
* find typical operation during startup/set-project to assure locking is granular enough (done).

## Preamble

Let's start with the 'world-building' if you will to help understand where conclusions are coming from.

### Goals

* Describe the kind of planned changes and *why they are there* (in terms of user value).
* Making the code more maintainable is a valid goal in itself
    - idiomatic and simple code that doesn't bypass the borrow-checker
* Try to find a way to achieve these changes with small PRs that can be merged quickly
    - Avoid sweeping changes to avoid conflicts, even though there might be ways to get unavoidable changes done as well.

### Application State

It's useful to start looking at what the application persists, and go from there. What follows was originally created by @krlvi and I adjusted it to fit the format.

#### The Project Directory

The "Project" is the user's Git repository that GitButler is visualising. GitButler is only interested in repositories with worktree, and their accompanying `.git` directory.

inside `.git/gitbutler` we have:

- ​**virtual\_branches.toml**​, managed from here https://github.com/gitbutlerapp/gitbutler/blob/master/crates/gitbutler-core/src/virtual\_branches/state.rs
- ​**operations-log.toml**​, managed from here https://github.com/gitbutlerapp/gitbutler/blob/master/crates/gitbutler-core/src/ops/state.rs (this one is just 2 values - a sha and a timestamp)

> [!NOTE]
> `virtual_branches.toml` is created when the project is added as it also contains information about which branch to merge with.

inside `.git` we still write 2 files only when there are merge conflicts:

- **base\_merge\_parent**
- ​**conflicts**​ (This bit is currently being reworked - the way gitbutler deals with merge conflicts, so both of these files will go away)

#### The Application Directory

inside `/Users/<user>/Library/Application Support/com.gitbutler.app/` :

- **projects.json** - this contains project/repo metadata & feature flags, managed from here https://github.com/gitbutlerapp/gitbutler/blob/master/crates/gitbutler-core/src/projects/storage.rs The plan for this is to move all of this to `.git/config` local to the repo and have it namespaced under [gitbutler]
- **user.json** - this is user metadata, login info, gitbutler cloud access token etc, managed from here https://github.com/gitbutlerapp/gitbutler/blob/master/crates/gitbutler-core/src/users/storage.rs
- **settings.json** - this contains global app settings that could not be on the user, it has only the user consent for error reporting & analytics. This is managed by Tauri and is only accessed from the frontend here: https://github.com/gitbutlerapp/gitbutler/blob/master/app/src/lib/config/appSettings.ts

This ☝️ is an **exhaustive** list of all of the **non-git** state of gitbutler, there's nothing else.

### Concurrency

The way it is right now.

#### On-Disk

Currently writes happen through a mechanism that assures that writes are complete or not done at all. It is implemented so that multiple writers race to completion, and the last-write wins.
This can lead to the application racing against itself or definitely against other instances.

Writes are always carried out against a single file, meaning that multiple files can be written in parallel, as long as proper coordination happens between them.

#### In-Memory

Rust helps to keep the in-memory concurrency in check thanks to the borrow-checker. This is only relevant, however, if it is not bypassed with interior mutability. The attempt to make everything in `core` `Send+Sync` to suit `tauri` now is a problem as everything can run concurrently, and everything can alter state even in `&self`. And while in-memory that's no problem as (blocking) locks are used, it's possible for writes to happen there as well, which are currently racy.

## Preliminary Conclusion

* on `tauri`-level, projects should be locked  permanently while it is considered open, using `fslock`.
    - prevents multi-app-instance access while eventually allowing this to be relaxed once app-instance can respond to all possible disk-changes accordingly.
    - *This means each in-memory-instance of what's stored on disk is actually a snapshot*
* While read-access should still be behind `&self`, each change now has to go through a `&mut` reference.
    - This way the application assures to not be able to racily write to disk as long as there is only one instance in-memory.
    - This can further be strengthened by forcing in-memory instance to hold an `fslock` on the file it reads from and writes to. Probably that should be the `Storage` implementation, held by `Controller` implementations.
         - Such an implementation must still be allowed to read even if it doesn't hold the lock, but writes must fail then.
* In `tauri`, RWLocks must now be wrapped around global instances of `Controllers`
    - That way, read-only operations can still happen in parallel, but writes cannot.
* *Optional refactor opportunities* (can happen at any time really)
    - use modules in such a way that names aren't duplicated.
    - Call `projects::Controller` `Projects` and get rid of one hierarchical level this way

### Benefits

If what's suggested in the preliminary conclusion would be done, what would be gained?

* A standard Rust codebase with the benefits of the borrowchecker for plumbing crates
* race-free both in memory and on disk
    - the on-disk part will help with Windows as well
* graceful support for multiple instances trying to see the same project
    - at first, it's forbidden, later one instance can certainly be read-only, which could be useful for multi-monitor setups.
* Can be done one controller at a time

## Bonus Points

* Think about how this facilitates multi-window handling
    - Can commands know about the window that calls them, and if so, can state be attached?
    - can `tauri` commands get parameters injected about additional state, like the current window or the project.
* **Lure out the essence of code**
    - How can boilerplate be removed, in `tauri` and maybe in `core`?
    - Can it be easier to write tests (and set them up)?

#### Can windows have meta-data attached to them?

Yes, by setting the Window ~~URL~~ label accordingly [during instantiation](https://docs.rs/tauri/latest/tauri/enum.WindowUrl.html#variant.App). It's immutable naturally.

It's also possible to additionally steer the Window to the project it needs, for instance by setting the initial URL to contain the project id.

Instead, one would need a multi-window approach with project-selector of sorts.
Alternatively, Windows with project-selectors cooperate and simply set focus if a project is already opened.

```rust
    let window = tauri::WindowBuilder::new(
        handle,
        "<project-id> or JSON serialized metadata",
        tauri::WindowUrl::App("index.html?project_id=bar".into()),
    )
```

The above already does something - it kicks right into the routing setup of the window's browser engine.

Tauri-commands can get the Window that invoked them by adding a `window: tauri::Window` parameter. Then the label with metadata could be read to figure out context.

It would also be possible to [evaluate javascript](https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.eval) to access javascript data, but obtaining a return value seems very indirect or difficult.

However, all these Window interactions require boilerplate code that ideally is avoided. Thus I think it's easier for the Window to automate its invocations to the backend such that some fields, like the project id, are always sent, and most commands are supposed to support it.

#### Can a `project_id` be turned into `ProjectContext` automatically?

No, not without having a separate command-wrapper of sorts that does the transformation. All we can retrieve is `State<T>` as identified by type, which is inherently not suited for runtime data. Thus, one will have to keep using a pre-amble of sorts on most/all commands that use a project_id. That, however, can certainly be streamlined a bit.

#### Can there be something like middleware?

Not in the sense that they could intercept invoked commands and modify them. Instead, they can read-only and get informed when windows are created or their URLs change. Thus they are somewhat more limited than middle ware is in a typical webserver framework.

#### Can state-parameters be injected via tauri command parameters?

Totally!

```patch
diff --git a/crates/gitbutler-tauri/src/projects.rs b/crates/gitbutler-tauri/src/projects.rs
index 25c970960..3b4529ba8 100644
--- a/crates/gitbutler-tauri/src/projects.rs
+++ b/crates/gitbutler-tauri/src/projects.rs
@@ -3,7 +3,7 @@ pub mod commands {
     use std::path;
 
     use gitbutler_core::projects::{self, controller::Controller, ProjectId};
-    use tauri::Manager;
+    use tauri::{Manager, State};
     use tracing::instrument;
 
     use crate::error::Error;
@@ -46,13 +46,14 @@ pub mod commands {
     ///
     /// We use it to start watching for filesystem events.
     #[tauri::command(async)]
-    #[instrument(skip(handle), err(Debug))]
-    pub async fn set_project_active(handle: tauri::AppHandle, id: ProjectId) -> Result<(), Error> {
-        let project = handle
-            .state::<Controller>()
-            .get(id)
-            .context("project not found")?;
-        Ok(handle.state::<Watchers>().watch(&project)?)
+    #[instrument(skip(watchers, ctrl), err(Debug))]
+    pub async fn set_project_active(
+        watchers: State<'_, Watchers>,
+        ctrl: tauri::State<'_, Controller>,
+        id: ProjectId,
+    ) -> Result<(), Error> {
+        let project = ctrl.get(id).context("project not found")?;
+        Ok(watchers.watch(&project)?)
     }
 
     #[tauri::command(async)]
```

Note that this also works for the `Window` that invoked the command, even though that should probably be done with care as to not tie commands to specifics of the Window (or any window, for that matter).

#### Does the frontend always have to go through the backend?

No, it can also get its own Window and mutate it, and of course, create new windows itself.

### The `fslock` crate

* The only usage of the `fslock` crate is in the `lock` module which is not used anymore.
* If `fslock` would be used as intended, it would be [able to spread `&mut`](https://docs.rs/fslock/latest/fslock/struct.LockFile.html#method.lock).
* This is the kind of lock one would use to protect against multiple instances.
    - As long as they don't respond to all relevant file-changes and thus go stale, a UI can be blocked entirely from opening an already opened project. Otherwise, a read-only mode would be possible, with write-permissions only given to the instance that holds the lock.
* The `lock` module shows that reads and writes to locked files are perfectly allowed at least while the lock is held.
    - still to be determined if reads are allowed while the lock is *not* held.

## Related Issues

These issues are positively affected or might even be resolved.

* #3861
* **one Window per project**
    - Maybe indirectly this benefits if all state and synchronization are extremely clear
* #3601
    - clearer locking and handling of concurrency within the application will avoid any race of the application instance itself

**Comment by Caleb-T-Owens** [comment]
@Byron 
> This ☝️ is an exhaustive list of all of the non-git state of gitbutler, there's nothing else.

We store non-git state in the user's git config (namely the AI auth keys) though that probably ought to be changed.

We also have various state stored in the browser's localstorage

**Comment by Byron** [comment]
> We store non-git state in the user's git config (namely the AI auth keys) though that probably ought to be changed.

This is a good reminder - races around any git-configuration file would be sorted by the Git implementation. And that now uses blocking lock-files, but it's racy nonetheless.

> We also have various state stored in the browser's localstorage. It would however be interesting to discuss whether storing things in localstorage is a good idea given that its not rust-accessable

From my point of view, that's a great thing as there is nothing to worry about. What does matter is how the backend handles the concurrent stream of possibly interleaved `tauri`-commands, which I think is maybe somewhat implicitly included in this issue. My take is that this is handled correctly naturally if the 'conclusion' would be enacted.

**Comment by Byron** [comment]
### Conclusions

Locking is now performed across processes so that no project can be observed or edited by more than one Window at once. Within this guarantee, in-process locking is used to prevent concurrent edits to the worktree of the project, while allowing concurrent reads using an `RwLock`.

This also means that within the codebase, most code is naturally `Send + Sync` as it interacts with resources on disk, with intermediate state being processed in memory and typically on a single thread only.

Using an `RwLock` also means that typically on a per-tauri-command basis, the right kind of lock, read or write, is acquired and the respective permission is passed down as needed. 
It's notable that some crate-internal (and maybe even public) functions aren't protected by permissions as they were only ever called while a lock was held anyway (for snapshot-related functions for example), so a practical route was chosen here to avoid having to adapt more tests than necessary.

The greatest risk of this system is that it is necessarily opt-in, and enforcement can only happen if functions use a `&WorktreeReadPermission` or `&mut WorktreeWritePermission` parameter, so it could deteriorate if developers aren't aware.

If you have any questions, in no particular order, @Caleb-T-Owens , @mtsgrd , @krlvi , @ndom91, @schacon, please do let me know.

### Some more notes

While working with `Worktree(Read|Write)Permission`, I liked how it would naturally propagate through the codebase, without ever having a chance to cause deadlocks as these are just markers, not actual locks. The lock itself can naturally be acquired per `tauri` command, which felt like the right place as well.

With these changes, one can now be confident that there will be no spurious bugs due to concurrency, which is the right state for more of `gitoxide` to be used in order to improve performance and compatibility, and ideally, also maintainability of the code.
